# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman"
gem "middleman-livereload", "~> 3.1.0"
gem "middleman-blog"
gem "rb-inotify", "~>0.9"
gem "middleman-smusher"
gem "middleman-syntax"
gem "middleman-sync"
gem "middleman-minify-html"
gem 'redcarpet'
