# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman"
gem "middleman-livereload"
gem "middleman-blog"
gem "rb-inotify"
gem "middleman-smusher"
gem "middleman-syntax"
gem "middleman-sync"
gem "middleman-minify-html"
gem 'redcarpet'
